In [1]:
from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    ShuffleSplit
)
from sklearn.linear_model import (
    LinearRegression,
    Lasso,
    Ridge
)
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import (
    RandomForestRegressor,
    AdaBoostRegressor, 
    GradientBoostingRegressor
)
from sklearn.neighbors import KNeighborsRegressor
from sklearn.naive_bayes import GaussianNB

from sklearn.metrics import r2_score

In [2]:
import pandas as pd
import numpy as np

train_df = pd.read_csv('Data/train.csv')
test_df = pd.read_csv('Data/test.csv')
data_df = pd.read_csv('Data/data.csv')

In [3]:
train_df

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-121.80,37.32,14.0,8.392310,6.829794,7.900637,6.793466,4.7027,227600.0,0,0,0,0
1,-119.63,36.64,33.0,6.944087,5.204007,6.431331,5.164786,3.4107,110400.0,1,0,0,0
2,-118.06,34.12,25.0,8.266678,6.744059,7.522400,6.633318,3.6639,248100.0,1,0,0,0
3,-118.31,34.07,28.0,7.767687,6.856462,7.922986,6.796824,2.2364,305600.0,0,0,0,0
4,-117.27,33.04,27.0,7.517521,5.973810,7.172425,6.003887,3.5500,214600.0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16341,-117.97,33.72,24.0,8.003697,6.216606,7.271009,6.118097,5.4286,273400.0,0,0,0,0
16342,-117.54,33.76,5.0,8.673684,6.943122,8.089176,6.909753,4.7965,160800.0,0,0,0,0
16343,-118.42,34.01,42.0,7.374629,5.913503,6.859615,5.894403,3.0990,335400.0,0,0,0,0
16344,-122.04,37.57,12.0,8.651724,6.970730,8.142354,6.964136,5.2879,231200.0,0,0,1,0
16345,-122.43,37.73,52.0,8.189522,6.605298,7.727976,6.473891,3.8934,251800.0,0,0,1,0

In [4]:
test_df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-117.24,32.79,20.0,6.869014,5.631212,6.265301,5.541264,3.1838,245800.0,0,0,0,1
1,-121.29,38.01,2.0,8.764678,7.018402,8.110127,6.864848,4.4871,137900.0,1,0,0,0
2,-118.14,33.92,31.0,8.224700,6.749931,7.746733,6.687109,3.2237,218200.0,0,0,0,0
3,-122.07,37.94,30.0,7.139660,5.624018,6.562444,5.402677,2.8920,220800.0,0,0,1,0
4,-121.89,37.99,4.0,7.683404,6.393591,6.834109,6.135565,4.1016,170500.0,1,0,0,0

In [5]:
data_df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,INLAND,ISLAND,NEAR BAY,NEAR OCEAN
0,-122.23,37.88,41.0,6.781058,4.867534,5.777652,4.844187,8.3252,452600.0,0,0,1,0
1,-122.22,37.86,21.0,8.867850,7.009409,7.784057,7.037906,8.3014,358500.0,0,0,1,0
2,-122.24,37.85,52.0,7.291656,5.252273,6.208590,5.181784,7.2574,352100.0,0,0,1,0
3,-122.25,37.85,52.0,7.150701,5.463832,6.326149,5.393628,5.6431,341300.0,0,0,1,0
4,-122.25,37.85,52.0,7.395108,5.638355,6.338594,5.560682,3.8462,342200.0,0,0,1,0

In [6]:
X = data_df.drop(['median_house_value'],axis=1)
y = data_df['median_house_value']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(16346, 12)
(16346,)
(4087, 12)
(4087,)

In [8]:
models = {
    'Linear Regression': LinearRegression(),
    'Ridge': Ridge(),
    'Lasso': Lasso(),
    'Decision Tree Regressor': DecisionTreeRegressor(),
    'Random Forest Regressor': RandomForestRegressor(),
    'Gradient Boosting Regressor': GradientBoostingRegressor(),
    'AdaBoost Regressor': AdaBoostRegressor(),
    # 'XGB Regressor': XGBRegressor(),
    # 'CatBoost Regressor': CatBoostRegressor(verbose=0)
}

In [9]:
params = {
    'Linear Regression': {
        'fit_intercept': [True, False]
    },
    'Ridge': {
        'alpha': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
    },
    'Lasso': {
        'alpha': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        'selection': ['cyclic', 'random']
    },
    'Decision Tree Regressor': {
        'criterion': ['squared_error', 'friedman_mse', 'absolute_error', 'poisson'],
        'splitter': ['best', 'random']
    },
    'Random Forest Regressor': {
        # 'n_estimators': [100, 200, 300, 400, 500],
        # 'criterion': ['squared_error', 'absolute_error']
    },
    'Gradient Boosting Regressor': {
        # 'n_estimators': [100, 200, 300, 400, 500],
        # 'loss': ['squared_error', 'absolute_error', 'huber', 'quantile']
    },
    'AdaBoost Regressor':{
        # 'n_estimators': [100, 200, 300, 400, 500],
        # 'learning_rate': [0.01, 0.05, 0.1, 0.3, 0.5]
    }

}

In [10]:
def evalute_model(X_train, X_test, y_train, y_test, models, params):
    score = []
    best_score = 0
    for model_name, model in models.items():
        print(f'Running {model_name} model...')
        cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=42)
        gs = GridSearchCV(model, params[model_name], cv=cv)
        print(f'Fitting {model_name} model...')
        gs.fit(X_train, y_train)
        y_pred = gs.predict(X_test)
        print(f'Evaluating {model_name} model...')
        test_model_score = r2_score(y_test, y_pred)
        score.append({
            'model': model_name,
            'score': test_model_score,
            'best params': gs.best_params_
        })
        if test_model_score > best_score:
            best_score = test_model_score
        print(f'{model_name} model completed...')
        model_df = pd.DataFrame(score)
    return model_df

In [11]:
best_model_df = evalute_model(X_train, X_test, y_train, y_test, models, params)

Running Linear Regression model...
Fitting Linear Regression model...
Evaluating Linear Regression model...
Linear Regression model completed...
Running Ridge model...
Fitting Ridge model...
Evaluating Ridge model...
Ridge model completed...
Running Lasso model...
Fitting Lasso model...
Evaluating Lasso model...
Lasso model completed...
Running Decision Tree Regressor model...
Fitting Decision Tree Regressor model...
Evaluating Decision Tree Regressor model...
Decision Tree Regressor model completed...
Running Random Forest Regressor model...
Fitting Random Forest Regressor model...
Evaluating Random Forest Regressor model...
Random Forest Regressor model completed...
Running Gradient Boosting Regressor model...
Fitting Gradient Boosting Regressor model...
Evaluating Gradient Boosting Regressor model...
Gradient Boosting Regressor model completed...
Running AdaBoost Regressor model...
Fitting AdaBoost Regressor model...
Evaluating AdaBoost Regressor model...
AdaBoost Regressor model completed...

In [14]:
best_model_df

,model,score,best params
0,Linear Regression,0.668360,{'fit_intercept': True}
1,Ridge,0.668772,{'alpha': 1}
2,Lasso,0.668631,"{'alpha': 5, 'selection': 'cyclic'}"
3,Decision Tree Regressor,0.684069,"{'criterion': 'poisson', 'splitter': 'best'}"
4,Random Forest Regressor,0.825837,{}
5,Gradient Boosting Regressor,0.766029,{}
6,AdaBoost Regressor,0.434926,{}

In [16]:
forest = RandomForestRegressor()
forest.fit(X_train, y_train)

RandomForestRegressor()

In [26]:
import os
import pickle

model_trainer_path = os.path.join('artifacts', 'model.pkl')

with open(model_trainer_path, 'wb') as file_obj:
    pickle.dump(forest, file_obj)

In [33]:
import json

json_file_path = os.path.join('artifacts', 'columns.json')

columns = {
    'data columns': [col.lower() for col in X.columns]
}

with open(json_file_path, 'w') as file_obj:
    file_obj.write(json.dumps(columns))